version: "3.8"

services:
  app:
    build: .
    environment:
      DATABASE_HOST: mtaa-db
      DATABASE_NAME: mtaa_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
    volumes:
      - ./app/:/home/mtaa/app/
    ports:
      - "8000:8000"
    depends_on:
      mtaa-db:
        condition: service_healthy

  mtaa-db:
    image: postgres:15.1-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - mtaa-db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 5432:5432
      
volumes:
  mtaa-db-data:
